update ci

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -20,3 +20,33 @@
 #       - cypress/screenshots
 #       - cypress/videos
 #     expire_in: 1 month
+
+# check:
+#   image: alpine:latest
+#   stage: check
+#   tags:
+#     - k8s
+#   rules:
+#     - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "staging" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "prod")'
+#   before_script:
+#     - apk update && apk add --no-cache curl jq
+#   script:
+#     - |
+#       info=$(curl --silent --header "PRIVATE-TOKEN: $TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/pipelines?ref=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" | jq '.[0]')
+      
+#       if [ "$info" = "null" ]; then
+#           echo "Previous pipeline not found"
+#           exit 0
+#       fi
+
+#       pipeline_status=$(echo "$info" | jq -r '.status')
+
+#       if [ "$pipeline_status" = "success" ]; then
+#           echo "Pipeline in the source branch passed. Merge to target branch allowed"
+#       else
+#           echo "Pipeline in the source branch not passed. Merge to target branch blocked"
+#           path=$(echo "$info" | jq -r '.web_url')
+#           echo 'URL of not passed pipeline:'
+#           echo "$path"
+#           exit 1
+#       fi
